from enum import StrEnum


class UserRole(StrEnum):
    CUSTOMER = "CUSTOMER"
    ADMIN = "ADMIN"


class SelectionSource(StrEnum):
    CURRENT_LOCATION = "CURRENT_LOCATION"
    ADDRESS_SEARCH = "ADDRESS_SEARCH"
    SAVED_POINT = "SAVED_POINT"
    MANUAL_MAP_SELECTION = "MANUAL_MAP_SELECTION"


class OrderStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_ADMIN_APPROVAL = "PENDING_ADMIN_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MISSION_PREPARING = "MISSION_PREPARING"
    MISSION_READY = "MISSION_READY"
    WAITING_FLIGHT_AUTHORIZATION = "WAITING_FLIGHT_AUTHORIZATION"
    MISSION_UPLOADING = "MISSION_UPLOADING"
    IN_TRANSIT = "IN_TRANSIT"
    AT_DESTINATION = "AT_DESTINATION"
    DELIVERED = "DELIVERED"
    RETURNING = "RETURNING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class MissionStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_VALIDATION = "PENDING_VALIDATION"
    GENERATED = "GENERATED"
    EXPORTED_TO_MISSION_PLANNER = "EXPORTED_TO_MISSION_PLANNER"
    UNDER_REVIEW = "UNDER_REVIEW"
    READY_FOR_AUTHORIZATION = "READY_FOR_AUTHORIZATION"
    AUTHORIZED = "AUTHORIZED"
    UPLOADING = "UPLOADING"
    UPLOADED = "UPLOADED"
    EXECUTING = "EXECUTING"
    DESTINATION_REACHED = "DESTINATION_REACHED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"
    RETURNING = "RETURNING"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"
    FAILED = "FAILED"


class AdminDecisionType(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AuthorizationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CONSUMED = "CONSUMED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class VehicleStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    OFFLINE = "OFFLINE"
    ONLINE = "ONLINE"
    BUSY = "BUSY"
    ERROR = "ERROR"


class EventSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class PaymentMethod(StrEnum):
    CREDIT_CARD = "CREDIT_CARD"
    PIX = "PIX"


class GatewayCommandType(StrEnum):
    ABORT = "ABORT"
    RTL = "RTL"


class GatewayCommandStatus(StrEnum):
    PENDING = "PENDING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
